window.GAME_DATA = {
  tracks: window.REAL_TRACK_CATALOG.map((track) => ({
    ...track,
    source: window.REAL_TRACK_LAYOUTS[track.layoutId].source,
    svgPath: window.REAL_TRACK_LAYOUTS[track.layoutId].path,
  })),
  weather: {
    clear: {
      label: "Seco",
      description: "Maximo grip y velocidad punta estable.",
      grip: 1,
      speed: 1,
      offTrack: 1,
      reward: 1,
      rain: false,
      tint: "rgba(255,255,255,0)",
    },
    rain: {
      label: "Lluvia",
      description: "Menos grip, mas spray y mejor recompensa por carrera.",
      grip: 0.79,
      speed: 0.96,
      offTrack: 1.2,
      reward: 1.2,
      rain: true,
      tint: "rgba(120,180,255,0.12)",
    },
    night: {
      label: "Noche",
      description: "Menos visibilidad, asfalto frio y ventaja ligera para turbo y energia.",
      grip: 0.93,
      speed: 1.02,
      offTrack: 1.05,
      reward: 1.12,
      rain: false,
      tint: "rgba(45,55,120,0.12)",
    },
  },
  upgrades: {
    engine: {
      label: "Motor",
      baseCost: 150,
      maxLevel: 5,
      description: "Mas velocidad punta y mejor aceleracion al salir de curvas.",
    },
    aero: {
      label: "Aero",
      baseCost: 140,
      maxLevel: 5,
      description: "Mas grip y mejor apoyo en cambios rapidos de direccion.",
    },
    armor: {
      label: "Blindaje",
      baseCost: 130,
      maxLevel: 5,
      description: "Sube la integridad maxima y reduce dano por golpes y debris.",
    },
    battery: {
      label: "Bateria",
      baseCost: 145,
      maxLevel: 5,
      description: "Mas energia disponible y recarga mas rapida para habilidades activas.",
    },
    magnet: {
      label: "I+D Magnetico",
      baseCost: 120,
      maxLevel: 5,
      description: "Aumenta el rango del iman y facilita recoger recursos sin perder trazada.",
    },
    tires: {
      label: "Neumaticos",
      baseCost: 150,
      maxLevel: 5,
      description: "Mas grip mecanico, mejor ventana en lluvia y menos castigo al tocar zonas sucias.",
    },
    brakes: {
      label: "Frenos",
      baseCost: 135,
      maxLevel: 5,
      description: "Mejora la frenada, la estabilidad en apoyo y el control al corregir errores.",
    },
    ers: {
      label: "ERS",
      baseCost: 155,
      maxLevel: 5,
      description: "Sube la regeneracion, abarata habilidades y alarga las ventanas electricas de ataque.",
    },
    drs: {
      label: "DRS",
      baseCost: 145,
      maxLevel: 5,
      description: "Hace mas fuerte el rebufo y aumenta la ganancia de velocidad en zonas DRS.",
    },
    suspension: {
      label: "Suspension",
      baseCost: 140,
      maxLevel: 5,
      description: "Reduce rebotes en pianos y bordes, y mejora la supervivencia fuera de trazada.",
    },
  },
  drivers: [
    { id: "lando-norris", name: "Lando Norris", shortName: "NOR", team: "McLaren", country: "GBR", flag: "gbr", number: "1", color: "#ff9e45", accent: "#51fff0", max: 314, accel: 226, brake: 265, steer: 2.36, grip: 0.95, lookAhead: 132, risk: 0.74 },
    { id: "oscar-piastri", name: "Oscar Piastri", shortName: "PIA", team: "McLaren", country: "AUS", flag: "aus", number: "81", color: "#ff9e45", accent: "#51fff0", max: 313, accel: 224, brake: 262, steer: 2.34, grip: 0.95, lookAhead: 130, risk: 0.68 },
    { id: "george-russell", name: "George Russell", shortName: "RUS", team: "Mercedes", country: "GBR", flag: "gbr", number: "63", color: "#28d7c7", accent: "#02231f", max: 313, accel: 224, brake: 264, steer: 2.35, grip: 0.95, lookAhead: 131, risk: 0.7 },
    { id: "kimi-antonelli", name: "Kimi Antonelli", shortName: "ANT", team: "Mercedes", country: "ITA", flag: "ita", number: "12", color: "#28d7c7", accent: "#02231f", max: 311, accel: 222, brake: 262, steer: 2.34, grip: 0.94, lookAhead: 132, risk: 0.64 },
    { id: "max-verstappen", name: "Max Verstappen", shortName: "VER", team: "Red Bull Racing", country: "NED", flag: "ned", number: "3", color: "#1f49ff", accent: "#f7d14a", max: 315, accel: 228, brake: 266, steer: 2.39, grip: 0.96, lookAhead: 136, risk: 0.86 },
    { id: "isack-hadjar", name: "Isack Hadjar", shortName: "HAD", team: "Red Bull Racing", country: "FRA", flag: "fra", number: "6", color: "#1f49ff", accent: "#f7d14a", max: 308, accel: 221, brake: 258, steer: 2.33, grip: 0.94, lookAhead: 126, risk: 0.67 },
    { id: "charles-leclerc", name: "Charles Leclerc", shortName: "LEC", team: "Ferrari", country: "MON", flag: "mon", number: "16", color: "#d92c2c", accent: "#ffe4e4", max: 312, accel: 223, brake: 264, steer: 2.36, grip: 0.95, lookAhead: 130, risk: 0.72 },
    { id: "lewis-hamilton", name: "Lewis Hamilton", shortName: "HAM", team: "Ferrari", country: "GBR", flag: "gbr", number: "44", color: "#d92c2c", accent: "#ffe4e4", max: 310, accel: 220, brake: 262, steer: 2.32, grip: 0.94, lookAhead: 128, risk: 0.61 },
    { id: "alexander-albon", name: "Alexander Albon", shortName: "ALB", team: "Williams", country: "THA", flag: "tha", number: "23", color: "#2b65ff", accent: "#ffffff", max: 305, accel: 217, brake: 254, steer: 2.31, grip: 0.93, lookAhead: 124, risk: 0.63 },
    { id: "carlos-sainz", name: "Carlos Sainz", shortName: "SAI", team: "Williams", country: "ESP", flag: "esp", number: "55", color: "#2b65ff", accent: "#ffffff", max: 306, accel: 218, brake: 255, steer: 2.32, grip: 0.93, lookAhead: 124, risk: 0.65 },
    { id: "liam-lawson", name: "Liam Lawson", shortName: "LAW", team: "Racing Bulls", country: "NZL", flag: "nzl", number: "30", color: "#eceff4", accent: "#1f49ff", max: 303, accel: 215, brake: 252, steer: 2.29, grip: 0.92, lookAhead: 121, risk: 0.6 },
    { id: "arvid-lindblad", name: "Arvid Lindblad", shortName: "LIN", team: "Racing Bulls", country: "GBR", flag: "gbr", number: "41", color: "#eceff4", accent: "#1f49ff", max: 302, accel: 216, brake: 250, steer: 2.31, grip: 0.92, lookAhead: 123, risk: 0.72 },
    { id: "fernando-alonso", name: "Fernando Alonso", shortName: "ALO", team: "Aston Martin", country: "ESP", flag: "esp", number: "14", color: "#1f7d57", accent: "#c6ff7c", max: 302, accel: 215, brake: 253, steer: 2.31, grip: 0.93, lookAhead: 125, risk: 0.62 },
    { id: "lance-stroll", name: "Lance Stroll", shortName: "STR", team: "Aston Martin", country: "CAN", flag: "can", number: "18", color: "#1f7d57", accent: "#c6ff7c", max: 297, accel: 210, brake: 247, steer: 2.24, grip: 0.91, lookAhead: 118, risk: 0.48 },
    { id: "esteban-ocon", name: "Esteban Ocon", shortName: "OCO", team: "Haas F1 Team", country: "FRA", flag: "fra", number: "31", color: "#f1f3f5", accent: "#d92c2c", max: 300, accel: 213, brake: 249, steer: 2.27, grip: 0.92, lookAhead: 120, risk: 0.55 },
    { id: "oliver-bearman", name: "Oliver Bearman", shortName: "BEA", team: "Haas F1 Team", country: "GBR", flag: "gbr", number: "87", color: "#f1f3f5", accent: "#d92c2c", max: 301, accel: 214, brake: 248, steer: 2.29, grip: 0.92, lookAhead: 122, risk: 0.66 },
    { id: "nico-hulkenberg", name: "Nico Hulkenberg", shortName: "HUL", team: "Audi", country: "GER", flag: "ger", number: "27", color: "#6b0f1a", accent: "#d9d9d9", max: 299, accel: 212, brake: 250, steer: 2.26, grip: 0.92, lookAhead: 121, risk: 0.52 },
    { id: "gabriel-bortoleto", name: "Gabriel Bortoleto", shortName: "BOR", team: "Audi", country: "BRA", flag: "bra", number: "5", color: "#6b0f1a", accent: "#d9d9d9", max: 300, accel: 213, brake: 249, steer: 2.28, grip: 0.92, lookAhead: 121, risk: 0.6 },
    { id: "pierre-gasly", name: "Pierre Gasly", shortName: "GAS", team: "Alpine", country: "FRA", flag: "fra", number: "10", color: "#2575ff", accent: "#ff68b3", max: 298, accel: 212, brake: 248, steer: 2.27, grip: 0.91, lookAhead: 120, risk: 0.58 },
    { id: "franco-colapinto", name: "Franco Colapinto", shortName: "COL", team: "Alpine", country: "ARG", flag: "arg", number: "43", color: "#2575ff", accent: "#ff68b3", max: 296, accel: 211, brake: 246, steer: 2.25, grip: 0.91, lookAhead: 118, risk: 0.56 },
    { id: "valtteri-bottas", name: "Valtteri Bottas", shortName: "BOT", team: "Cadillac", country: "FIN", flag: "fin", number: "77", color: "#0f3d7a", accent: "#f4d36d", max: 295, accel: 209, brake: 246, steer: 2.24, grip: 0.9, lookAhead: 118, risk: 0.46 },
    { id: "sergio-perez", name: "Sergio Perez", shortName: "PER", team: "Cadillac", country: "MEX", flag: "mex", number: "11", color: "#0f3d7a", accent: "#f4d36d", max: 296, accel: 210, brake: 247, steer: 2.25, grip: 0.91, lookAhead: 119, risk: 0.54 },
  ],
};
